### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by jomahoney** [irccloud/android#170]
Every time I try to launch the app it crashes immediately without even rendering a screen. I will admit I'm using [MicroG](https://lineage.microg.org/) so not directly connected to any google services. The crash looks independent of this fact though.

Device: OnePlus 5
OS: Lineage 15.1-20181203-microg-cheeseburger
Android version: 8.1.0

Crash:
```
--------- beginning of crash
12-07 09:27:05.444 23402 23402 E AndroidRuntime: FATAL EXCEPTION: main
12-07 09:27:05.444 23402 23402 E AndroidRuntime: Process: com.irccloud.android, PID: 23402
12-07 09:27:05.444 23402 23402 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.irccloud.android/com.irccloud.android.activity.LoginActivity}: android.view.InflateException: Binary XML file line #42: Binary XML file line #42: Error inflating class android.widget.ImageView
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #42: Binary XML file line #42: Error inflating class android.widget.ImageView
12-07 09:27:05.444 23402 23402 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #42: Error inflating class android.widget.ImageView
12-07 09:27:05.444 23402 23402 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:419)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.Activity.setContentView(Activity.java:2669)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at com.irccloud.android.activity.LoginActivity.onCreate(LoginActivity.java:133)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7009)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7000)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Drawable (missing name) with resource ID #0x7f0800cf
12-07 09:27:05.444 23402 23402 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0800cf
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:253)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:760)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:630)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.content.res.Resources.loadDrawable(Resources.java:886)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:953)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.widget.ImageView.<init>(ImageView.java:188)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.widget.ImageView.<init>(ImageView.java:171)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.widget.ImageView.<init>(ImageView.java:167)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:419)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.Activity.setContentView(Activity.java:2669)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at com.irccloud.android.activity.LoginActivity.onCreate(LoginActivity.java:133)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7009)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7000)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
12-07 09:27:05.444 23402 23402 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
12-07 09:27:06.062  1190  3547 W ActivityManager:   Force finishing activity com.irccloud.android/.activity.LoginActivity
12-07 09:27:06.066  1190  1244 I ActivityManager: Showing crash dialog for package com.irccloud.android u0
12-07 09:27:06.564  1190  1241 W ActivityManager: Activity pause timeout for ActivityRecord{a47777 u0 com.irccloud.android/.activity.LoginActivity t4118 f}
12-07 09:27:06.682 23402 23436 I CrashlyticsCore: Crashlytics report upload complete: 5C0A3CE9005F-0001-5B6A-918ED0DFC1EA
12-07 09:27:16.877  1190  1241 W ActivityManager: Activity destroy timeout for ActivityRecord{a47777 u0 com.irccloud.android/.activity.LoginActivity t4118 f}
12-07 09:27:16.888  1190  1241 W ActivityManager: Activity destroy timeout for ActivityRecord{53a3566 u0 com.irccloud.android/.activity.MainActivity t4118 f} 
```

**Comment by c99koder** [comment]
Hi John,

The app is crashing because you've side-loaded an incomplete APK.  Please install the app properly using the Play Store so all the bundle components get downloaded for your device configuration.

Thanks,
--
Sam Steele
Mobile Developer
IRCCloud, Ltd.
